### ISSUE TITLE
\FluidTYPO3\Fluidpages\Provider\PageProvider::loadRecordTreeFromDatabase does not check if returned record from recordService is null

### ISSUE THREAD

**Issue by wazum** [FluidTYPO3/fluidpages#392]
If
`$record = $this->recordService->getSingle($this->getTableName($record), '*', $record[$parentFieldName]);
`
returns null (e.g. one of the parent records is set to _deleted_), this leads to an exception.

**Comment by NamelessCoder** [comment]
This isn't exactly related to the patch you did, but if you're experiencing this problem that would indicate you're trying to view or edit a page that *does not exist anywhere in the page tree*. Additionally it indicates that the page actually wasn't deleted with TYPO3 because it would have restricted deletion if there were active sub-pages (and if recursive deletion was allowed in user settings, it would've deleted the child pages first afaik).

There might be something more to explain *why* you're actually experiencing this issue. Technically, it shouldn't be possible to experience this if you manage the pages in normal ways through TYPO3.

That said, the code does return null from this method and this has to be handled. Just be aware that something else is probably broken on your setup ;)

**Comment by wazum** [comment]
@NamelessCoder  Certainly possible, it's a large installation with some upgrades already, and the problem occurs when running the reference index check/update … (actually prevents it from running …)

**Comment by GertHammes** [comment]
@wazum I get an error at the same line when opening pages in the frontend (TYPO3 8.7.22, flux 9.1.0 + fluidpages 4.3.0). The page definitely exists in the page tree. The error occurrs if i open a page in the frontend whose parent page is marked as hidden.
I get the error message _Argument 1 passed to FluidTYPO3\Flux\Provider\AbstractProvider::getParentFieldName() must be of the type array, boolean given_.
The documented return type of \FluidTYPO3\Flux\Service\RecordService::getSingle is not correct, the actual return type is array|null|boolean because the reset returns false if the array is empty.
Your commit only checks for `null !== $record`. Since this is the same issue, can you please update the condition in your pull request to `!empty($record)`

**Comment by wazum** [comment]
@GertHammes I updated the pull request

**Comment by NamelessCoder** [comment]
Fixed via https://github.com/FluidTYPO3/fluidpages/commit/74f5fdfb29ef75686b60767472bfb5a0c9e2c4bb.

**Comment by franzkugelmann** [comment]
For me the change in 74f5fdf does not fix the issue, but just result in a different error:
> Tried resolving a template file for controller action "Page->default" in format ".html", but none of the paths contained the expected template file ().

If the parent page is hidden, and the current page tries to get the PageLayout from higher up in the rootline, the Layout cannot be found because in RecordService::getSingle() the enableFields (hidden, startTime, endTime) are taken into account and the rootline is broken. Always using BackendUtility::getRecord() fixed that. 
Not sure if that triggers problems at other locations of the code where the record of a hidden page should really NOT be loaded.

**Comment by NamelessCoder** [comment]
@franzkugelmann This is not the same issue. Two other issues are potentially related: https://github.com/FluidTYPO3/fluidpages/commit/2a269ce8b8f02183a8155718121ae4ef2bcf9ee3 (merged) and https://github.com/FluidTYPO3/fluidpages/pull/411 (not merged, may be hidden by the other issue, only applies on certain setups).
